ASYMP_RATE: 0.179
CITY: Beaumont-Port_Arthur
CLOSE_TRIGGER_LIST:
- date__20200319
CONTACT_REDUCTION:
- 0.0
DATA_FOLDER: ./data/Cities_Data/
DOUBLE_TIME:
  high: 4.0
  low: 7.2
D_RELATIVE_RISK_IN_HIGH: 10
GROWTH_RATE_LIST:
- high
HIGH_RISK_RATIO:
  0-4: 8.2825
  18-49: 16.5298
  5-17: 14.1121
  50-64: 32.9912
  65+: 47.0568
H_FATALITY_RATIO:
  0-9: 0.0
  10-19: 0.2
  20-29: 0.2
  30-39: 0.2
  40-49: 0.4
  50-59: 1.3
  60-69: 3.6
  70-79: 8
  80+: 14.8
H_RELATIVE_RISK_IN_HIGH: 10
I0:
- - 0
  - 0
- - 0
  - 0
- - 1
  - 0
- - 0
  - 0
- - 0
  - 0
INFECTION_FATALITY_RATIO:
  0-9: 0.0016
  10-19: 0.007
  20-29: 0.031
  30-39: 0.084
  40-49: 0.16
  50-59: 0.6
  60-69: 1.9
  70-79: 4.3
  80+: 7.8
NUM_SIM: 1
OVERALL_H_RATIO:
  0-9: 0.04
  10-19: 0.04
  20-29: 1.1
  30-39: 3.4
  40-49: 4.3
  50-59: 8.2
  60-69: 11.8
  70-79: 16.6
  80+: 18.4
PROP_TRANS_IN_E: 0.126
R0: 2.2
REOPEN_TRIGGER_LIST:
- no_na_{{FallStartDate}}
RESULTS_DIR: ./outputs
T_EXPOSED_PARA:
- 5.6
- 7
- 8.2
T_H_TO_D: 14.0
T_H_TO_R: 14.0
T_ONSET_TO_H: 5.9
T_Y_TO_R_PARA:
- 21.1
- 22.6
- 24.4
age_group_dict:
  3:
  - 0-4
  - 5-17
  - 18+
  5:
  - 0-4
  - 5-17
  - 18-49
  - 50-64
  - 65+
beta0_dict:
  high: 0.0351655
deterministic: true
fit_bounds:
  c_reduction:
  - 0.0
  - 1
fit_guess:
  c_reduction: 0.5
fit_var_names:
- c_reduction
hosp_data_fp: data/hospitalization/2020-04-20/hosp_setrac_beau_msa_20200420.csv
interval_per_day: 10
is_fitting: true
monitor_lag: 0
n_age: 5
n_risk: 2
report_rate: 1.0
sd_date:
- 20200328
- 20200818
shift_week: 0
time_begin_sim: '20200225'
total_time: 150
trigger_type: cml
verbose: false
